spring.application.name=project-module
spring.datasource.url=jdbc:postgresql://localhost:5432/kunsthaben_db
spring.datasource.username=postgres
spring.datasource.password=1qaz
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect